### ISSUE TITLE
Needs updates.

### ISSUE THREAD

**Issue by javydekoning** [dmariogatto/choco#1]
Hi, package seems outdated. Could we automate updates with GitHub actions or another CI tool?

**Some suggestions:**

Get latest release:
```
curl -s 'https://www.amd.com/en/support/chipsets/amd-socket-am4/b450' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:82.0) Gecko/20100101 Firefox/82.0' | lynx -stdin -dump | grep -m 1 drivers.amd.com/drivers/amd_chipset_software_ | cut -d ' ' -f 3
```

Download:
```
curl {{output from above}} -o some.file -H 'Referer: https://www.amd.com/en/support/chipsets/amd-socket-am4/b450'
```

Get SHA:
```
sha256sum some.file
```

Using actions we can have it run on a schedule, and [automatically create a new branch](https://github.com/Automattic/action-commit-to-branch) + PR. Schedule:

```yaml
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
```

Happy to help out should you want or need help :)
